set(QT_REPO_MODULE_VERSION "6.11.1")
set(QT_REPO_MODULE_PRERELEASE_VERSION_SEGMENT "alpha1")

set(QT_EXTRA_INTERNAL_TARGET_DEFINES
    "QT_ENABLE_STRICT_MODE_UP_TO=QT_VERSION_CHECK(6,11,0)"
    # The following flags are not yet part of the strict mode
    "QT_LEAN_HEADERS=1"
    "QT_NO_CAST_FROM_ASCII=1"
    "QT_NO_QPAIR=1"
)
